# Generated by Django 5.1.1 on 2024-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CulturewalkTable",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("ctprvn_nm", models.CharField(max_length=255)),
                ("signgu_nm", models.CharField(max_length=255)),
                ("legaldong_nm", models.CharField(max_length=255)),
                ("fclty_nm", models.CharField(max_length=255)),
                ("mlsfc_nm", models.CharField(max_length=255)),
                ("adr_nm", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "culturewalk_table",
            },
        ),
    ]
